query device_info($device: String!) {
  InfraDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        interfaces {
          edges {
            node {
              name {
                value
              }
              enabled {
                value
              }
              mtu {
                value
              }
              status {
                value
              }
              speed {
                value
              }
            }
          }
        }
      }
    }
  }
}